"""
backend/api/models/base.py
==========================
Declarative base and shared column mixins used across all ORM models.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """
    Project-wide SQLAlchemy declarative base.
    All ORM models inherit from this class.
    """
    pass


class UUIDPrimaryKeyMixin:
    """
    Mixin that adds a UUID primary key generated by PostgreSQL's
    gen_random_uuid() (requires pgcrypto extension).
    Using server-side generation means the DB is the source of truth
    and we avoid UUID collisions in distributed workers.
    """
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        index=True,
    )


class TimestampMixin:
    """
    Mixin that adds created_at / updated_at columns.
    Both are set by PostgreSQL triggers so they are reliable even
    when rows are mutated outside the ORM (e.g., raw SQL migrations).
    """
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )